### ISSUE TITLE
Features of datasets

### ISSUE THREAD

**Issue by Cantoria** [snap-stanford/CAW#3]
Hi dear authors,
I have noticed that the processed file contains node features and edge features for all datasets. As far as I know, the original ENRON/UCI/social-evolution datasets do not contain any node/edge features. I have checked your paper, but the paper doesn't mention any details for initializing node or edge features. Can you describe the details of initializing node or edge features in these .npy files? Thanks!

**Comment by lipan00123** [comment]
I guess we initialize them as constant features to guarantee the model is inductive.

**Comment by Cantoria** [comment]
> I guess we initialize them as constant features to guarantee the model is inductive.

How to initialize features of three datasets? randomly initialize?

**Comment by lipan00123** [comment]
We used "constant" features as initial features. We have tried random initialization, which typically gives better transductive learning performance, worse inductive learning performance and the model converges slow.

**Comment by Cantoria** [comment]
> We used "constant" features as initial features. We have tried random initialization, which typically gives better transductive learning performance, worse inductive learning performance and the model converges slow.

Thanks for your reply. You would better mention this in your paper.

**Comment by lipan00123** [comment]
One thing should be emphasized that. Our method does not need node features at all as we may capture the structural dynamics.
