### ISSUE TITLE
auc and ap swapped

### ISSUE THREAD

**Issue by VictorTiezzi** [snap-stanford/CAW#5]
in the log the results are changed

https://github.com/snap-stanford/CAW/blob/0aab882633868c83ad3b8071b0bd560bfd1209d1/main.py#L142
https://github.com/snap-stanford/CAW/blob/0aab882633868c83ad3b8071b0bd560bfd1209d1/main.py#L144

**Comment by Abel0828** [comment]
Hi thanks so much for posting the issue! We are sorry for having made this typo. The code has been updated. Meanwhile, please rest reassured that the results reported remain unaffected since they were collected through (l-152) save_oneline_result.
